kind: Job
apiVersion: batch/v1
metadata:
  name: postgres-pg-extension-job
  labels:
    component: postgres-pg-extension-job
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      name: postgres-pg-extension-pod
      creationTimestamp: null
      labels:
        component: postgres-pg-extension-job
        job-name: postgres-pg-extension-job
    spec:
      containers:
        - name: postgres-client
          image: 'quay.io/openshift/origin-cli:latest'
          command:
            - /bin/sh
            - '-c'
          args:
            - >
              podname=$(oc get pods -l app=postgresql -o
              jsonpath='{.items[0].metadata.name}')

              echo $podname

              oc rsh -c postgresql $podname psql -d vectordb -c 'CREATE
              EXTENSION vector;'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: postgres-service-account
      serviceAccount: postgres-service-account
      securityContext: {}
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false
