kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: llm-ui
  labels:
    app: gradio-hftgi-rag-redis
spec:
  to:
    kind: Service
    name: gradio-hftgi-rag-redis-model1
    weight: 50
  alternateBackends:
    - kind: Service
      name: gradio-hftgi-rag-redis-model2
      weight: 50
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
