apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: on-pullrequest
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/task: "[git-clone, buildah]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"

spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  taskRunSpecs:
    - pipelineTaskName: build
      taskServiceAccountName: pipelines-sa-userid-1000
    - pipelineTaskName: push-to-quay
      taskServiceAccountName: pipelines-sa-userid-1000
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: images-url
      emptyDir: {}
