apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: vectordb
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  databasePort: 10225
  memorySize: 3GB
  modulesList:
    - name: search
      version: 2.8.12
  persistence: disabled
  replication: true
  tlsMode: disabled
  type: redis
